version: "3"
services:
  accounts-service-server:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PORTS=3000
    ports:
      - PORTS=3000:3000
    command: node index.js