version: "3"
services:
  accounts-service-server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORTS=3000
    ports:
      - "3000:3000"
    command: npm run dev